name: Backend CI

on:
  push:
    paths:
      - '../../backend/**'
    branches: [ production, dev ]
  pull_request:
    paths:
      - '../../backend/**'
    branches: [ production, dev ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin' # AdoptOpenJDK has been moved to Eclipse Temurin
          cache: maven
      - name: Build with Maven
        run: mvn clean install --file backend/pom.xml
      - name: Run Spring Boot tests
        run: mvn test --file backend/pom.xml
