name: deploy wudget
run-name: deploy wudget

on:
  push:
    branches:
      - production

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: code checkout
        uses: actions/checkout@v2

      - name: install the gcloud cli
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: build and push docker image
        env:
          GOOGLE_PROJECT: ${{ secrets.GCP_PROJECT_ID }}
        run: |
          gcloud auth configure-docker europe-west4-docker.pkg.dev
          docker build -t europe-west4-docker.pkg.dev/wudget/wudget-repository/wudget-front-end:latest ./frontend
          docker push europe-west4-docker.pkg.dev/wudget/wudget-repository/wudget-front-end:latest
          docker build -t europe-west4-docker.pkg.dev/wudget/wudget-repository/wudget-back-end:latest ./backend
          docker push europe-west4-docker.pkg.dev/wudget/wudget-repository/wudget-back-end:latest
